### ISSUE TITLE
query-exporter cache expired metrics

### ISSUE THREAD

**Issue by lihaiswu** [albertodonato/query-exporter#26] opened 2020-02-22 23:39 UTC
**Describe the bug**
query-exporter will always cache expired metrics from db unless the query-exporter restarted

**Installation details**
- operating system: kubernetes
- query-exporter installation type:
  - [ ] pip: [output from `pip list`]
  - [x] docker image: adonato/query-exporter:2.0.2
  - [ ] snap: [output from `snap list | grep query-exporter`]

**To Reproduce**
1. create database test in postgres. It has table pipeline and query metrics with following sql:
SELECT pipeline_starttime_seconds, environment, pipelineid, pipelinename  FROM pipeline WHERE pipeline._start_time >= (NOW() - INTERVAL '2 DAYS')
From query-exporter endpoints, I can see  the metrics which matches to the sql output. Like:
pipeline_starttime_seconds{database="test",environment="staging",pipelineid="5e4c22125282e765b7cbdf3f",pipelinename="job_name"} 1.582047762272e+09

2. after one day, the pipelineid 5e4c22125282e765b7cbdf3f is not in the output of same sql "SELECT * FROM pipeline WHERE pipeline._start_time >= (NOW() - INTERVAL '2 DAYS')" since pipeline._start_time was expired. That's expected.

3. However, the same metric in 1 still existed in query-exporter endpoints. Looks like query-exporter always keep the old metrics even the sql output does not have the records.

4. After restarting the query-exporter container, then the metric in 1 was gone. 

I think the query-exporter should match to the sql result. Otherwise, it'll accumulate the metrics by the up of query-exporter. Most of metrics are never used since they're not from the output of sql. And some old metrics may mess up the alerts.

@albertodonato Could you please take a look when you get a chance? Thanks a lot!

**Comment by albertodonato** [comment] 2020-02-23 11:00
Hi, thanks for the report.

What you described is expected behavior, the `prometheus_client` library accumulates series over time, as there is no concept of a "closed" series (it's always possible that a series with a certain combination of lables will have samples in the future).
This should not be an issue for Prometheus which should detech which series have changed from the last scrape (based on timestamps).

I'm not very familiar with alerts but I don't think there should be a problem with those, again because they should consider timestamps for changed.

Have you seen any issue with those?

**Comment by lihaiswu** [comment] 2020-02-23 18:05
@albertodonato thanks for looking into it. For inexistent records(metrics) returned from sql, do we need to keep them? If so, the total size of metrics collected by query-exporter will increase day by day until query-exporter restart and cleanup "old" data. It seems prometheus gateway(https://github.com/prometheus/pushgateway) did accumulate series overtime and always keep the old data, like what did in query-exporter. But I just test with Jenkins prometheus plugin(https://github.com/jenkinsci/prometheus-plugin), and this plugin will remove  job metrics when the job is deleted:

1. Create a sample job test in jenkins
2. Access prometheus endpoint http://jenkins/prometheus/. I can see some metrics related to job test
3. Delete job test in jenkins
4. Wait for a few minutes, access http://jenkins/prometheus/ again. I can see there's no any metrics related to job test

From query-exporter side, since it retrieves the records from database. I'd like to see the metrics match to actual db result and no need to keep old metrics like what jenkins prometheus plugin did. Suppose that, we remove a record in database. Then query-exporter should not contain the metrics. From prometheus side, this time series may show no data for this deleted record. So that we know this record is gone.

I'm not sure if query-exporter can expose an option, so that user can decide which behavior to use: 

1. default behavior: accumulates series over time (what current query-exporter did)
2. refresh behavior: refresh metrics to match sql output ( just like the first time of sql which metrics match to actual sql output and no need keep inexistent metrics). Like jenkins prometheus plugin did.

**Comment by albertodonato** [comment] 2020-02-23 18:45
The use case you mentioned seems pretty similar to others described inhttps://github.com/prometheus/client_python/issues/182.
As said there, it's expected for series to live throughout the life of the application.

I don't think what you're suggesting is possible as it is, because metrics are not necessarily collected from the database on request (in cases where an `interval` is specified), so there's no single moment in which to reset metrics.
A possible improviment (as mentioned on that issue) would be to use a custom collector in query-exporter, which ignores samples that are older then a certain interval.

I'm not totally sure how useful that would be, though. It might reduce memory usage for the exporter over a long period, assuming old series are discarded, but it won't make any difference on the Prometheus side.

**Comment by lihaiswu** [comment] 2020-02-23 19:00
@albertodonato yes, it's similar to the issue you pointed. Since I use Telegraf to pull the metrics from query-exporter and foward to other vendors(wavefront). The Telegraf has setting for the metric_buffer_limit (https://github.com/helm/charts/blob/master/stable/telegraf/values.yaml#L93). As time goes, the query-exporter metrics body may exceed  metric_buffer_limit and cause some metrics discard, that's why I do not want to keep the inexistent metrics and just query specific range of db records. So far, I need to restart query-exporter after running for few days to cleanup the inexistent metrics.

**Comment by kduvekot** [comment] 2020-04-10 08:56
I think it would be good if "old" metrics are cleanup .. but don't make it a service wide option . but specify it on the metric definition.

if the SQL doesn't return any value for a previous metric/label combination .. remove that metric/label combination from the metrics store.
that way you can do a compare between SQL result and exiting metrics .. and create the necessary removal of the "stale" metrics.

**Comment by invokermain** [comment] 2020-07-17 10:36
I agree this feature would very useful, for example when running a query that only returns rows when you want to alert, as well as the concerns mentioned above. I also understand that it's slightly weird from a Prometheus perspective, but honestly Prometheus + an exporter like this is one of the best ways to alert off of SQL.

I am very happy to try and PR this? At my company we have a handful of alerts that fit this pattern, just need to figure out what is wrong with my Docker set up.

**Comment by searchgithub** [comment] 2020-07-27 01:44
we agree to do the "switch" to do the clean up the data

**Comment by lihaiswu** [comment] 2020-07-27 18:26
> we agree to do the "switch" to do the clean up the data

Could you explain on how to do the "switch"? Do you mean redeploy the db-query?

**Comment by invokermain** [comment] 2020-08-03 08:58
I think this is possible by implementing a custom collector which caches the metrics seen when a query is run and then (optionally) removes them from the collection when the query is next run and the metric is not seen.

Doing it per-query would allow it to handle the multiple queries per metrics pattern (although might not support all use cases).

**Comment by chitrosu** [comment] 2020-08-11 11:16
Hello guys,
I have encountered the same problem. The exporters retains the old metrics even if the entries are not in the database anymore, or if the entries are not anymore returned by queries.

So I think would be useful to be able chose (by using an option on metric definition) what metrics should be retained in the metric store of query-exporter when the entry is not returned anymore by the SQL query.

Regards,

**Comment by AKYD** [comment] 2020-08-12 11:57
The problem is only for Gauges, since counters, summaries and histograms are not really used "raw", but via increase, rate, etc.

Gauges should reflect the **current** state of whatever they measure. Returning old values breaks this.
Once the old (A) and new (B) timeseries are ingested by Prometheus how do we know that we shouldn't rely on the A value anymore since it represents something that's long gone and not current anymore?

**Comment by willgorman** [comment] 2020-12-09 16:47
I think it might be helpful for gauges to return 0 for any series that exists but that no longer has any records found in the database by the query.

**Comment by ryjogo** [comment] 2021-02-03 18:55
I recently came across this issue in a recent deployment of the exporter. My (very rough) work around was to restart the exporter every night, which is undesirable. I would be great to have a cache expiry mechanism on this.

**Comment by NorseGaud** [comment] 2021-03-26 00:30
+1 for this. Having to restart the exporter is painful.

**Comment by NorseGaud** [comment] 2021-03-26 01:29
Actually, I switched to GuageVec and then just use metric.Reset() now. Here is what I do: https://github.com/veertuinc/anka-prometheus-exporter/blob/efda1f39ce9d233d870910dca99c5007cfea17be/src/metrics/utils.go#L116

**Comment by albertodonato** [comment] 2021-03-26 07:57
Does that refresh a metric as a whole or by specific set of labels?

The original issue is about having stale label combinations in case you have a label with values that don't repeat (like unique IDs).
Handling that is tricky with the current implementation of the Prometheus python lib as the collector is called only when metrics are requested, not when they're added (where it would be easier to add timestamps).

So to support this it requires some changes in the lib.

**Comment by sylvaindd** [comment] 2021-03-26 13:06
+1 Really could use this feature too.

**Comment by invokermain** [comment] 2021-03-27 00:15
Trying to get this thread moving towards a solution...

I've found a way this could work and have no clue if it is a good idea or pure hack. This method assumes a given metric will only ever be returned by a single query. I'm guessing this assumption isn't true and you could have two separate queries that update the same metric?

Anyway have a look at [this fork](https://github.com/albertodonato/query-exporter/compare/master...invokermain:master) @albertodonato. I will not spend anymore time on it without your feedback... you will be a much better judge of its worth than me. But if you think it's viable I am happy to work on it further.

I have tested this (briefly, and after some wine) using the following config:

```yaml
databases:
  db1:
    dsn: sqlite://
    keep-connected: false

metrics:
  metric1:
    type: gauge
    description: A sample gauge
    forgetful: true
    labels: [label1]
  metric2:
    type: gauge
    description: A sample gauge2
    labels: [label1]

queries:
  query1:
    interval: 15
    databases: [db1]
    metrics: [metric1, metric2]
    sql: |
      SELECT strftime('%S','now') label1, strftime('%S','now') AS metric1, 10 + strftime('%S','now') AS metric2
      UNION ALL
      SELECT 60 - strftime('%S','now') label1, 60 - strftime('%S','now') AS metric1, 15 + strftime('%S','now') AS metric2
```

**Comment by albertodonato** [comment] 2021-03-27 07:31
@invokermain thanks for taking a look into it.

Unfortunately just marking the metric that way is not enough for a generic solution.
First of all, it should work for all metric types, secondly, it needs to consider each series (set of label values) individually.

The idea is that for a given metric you could have values for `mymetric{a="foo",b="bar"}` and `mymetric{a="baz",b="bar"}`, and after a while only the latter is updated, because the first series is no longer seen. To avoid ending up with a lot of stale combinations, it'd have to track the last time each set has been updated, and drop cached samples for stale series.

Likely this require extending the Prometheus python library since it currently doesn't track sample timestamps (although there seem to be some support for it).

I'll try to investigate it a bit further, I'd like to get support for this too.

**Comment by invokermain** [comment] 2021-03-27 21:31
Yeah, agreed that my method is too naïve. My first attempt was to track series but this ended up being so ugly that it felt like the wrong approach. But I believe it shows you don't need to extend the Prometheus python library to achieve this behaviour.

The more I think about it though the more complicated it gets with the fact that 1) different queries can return the same metrics 2) queries can either be ran on schedule or on http request.

Could something like this potentially work?
- When a series is first seen, store it's hash (or whatever), and calculate the time you would next expect to see it, call it `expected_by` (to get around multi query same metric issue).
  - So if it was seen in a query with interval 1 minute calculate now + 1 minute. 
  - If it was an http request query ignore this.
- If you the series has already been seen, recalculate `expected_by` and update the value if the new value is further in the future than the current value.
- As late as possible, when the metrics have been requested (after running instant queries etc). Clear series from the metrics (and cache) that have not been seen and it's gone past their `expected_by` value.

You should just be able to call `metric.remove(*series.values())`, [see here](https://github.com/prometheus/client_python/blob/master/prometheus_client/metrics.py#L178).

**Comment by albertodonato** [comment] 2021-03-28 00:06
The `metrics.remove()` is interesting. Something like that could possibly work, but I think it needs to be a bit more flexible.
Basically I'd like to be possible to define an "expiration" per-metric,
I doubt you can actually have an expected_by, because there's no guarantee on the time a scrape is called for non-periodic calls, and also for the periodic ones, you can have more than one query updating the same metric at different times.

So I think the only way is to track times for last update for each (metric, labels), and clear stale ones before generating results on scrape.

Anyway, this seems at least a path forward, thanks for the idea, I'll try to take a look at it

**Comment by invokermain** [comment] 2021-03-28 01:07
No problem, I really like what I have seen of this exporter so far, will definitely make my life easier compared to other SQL exporter I use at the moment when I switch (but I require this functionality unfortunately).

An 'expires in' value per metric would definitely solve my use case (and I imagine the general alerting off SQL queries using Prometheus case). I would just set 'expires in' to 0, and only ever have a single query for each metric anyway.

I think it also handles the one metric multiple queries (with different intervals, or no interval) case as well because you can just be clear that if your 'expires in' value is shorter than the longest interval will probably cause weird behaviour. Good luck!

**Closed** 2021-03-28 08:48 UTC
Labels: enhancement

**Comment by albertodonato** [comment] 2021-03-28 08:50
Thanks @invokermain for the pointers, it turned out that it wasn't too hard to implement tracking and cleaning up expired metrics using `metric.remove()`.

I might have some further cleanups but what's in master now should be enough to support the mentioned scenarios.

**Comment by sylvaindd** [comment] 2021-03-28 15:32
Thank you, are you going to make a new release ?

**Comment by albertodonato** [comment] 2021-03-28 18:30
Yep, done now.

**Comment by sylvaindd** [comment] 2021-03-30 17:33
It's working for me, thank you !

**Comment by Aliaksei-Halouka** [comment] 2021-11-16 09:15
It looks like I also encountered metric caching, the exporter continues to pass the value even if the SQL query no longer returns the given metric. But I don't understand what that has to do with it, it's been fixed, hasn't it? Used version 2.7.0

**Comment by invokermain** [comment] 2021-11-16 10:09
@Aliaksei-Halouka have you set the expiration value on the metric as it suggests in the docs?

**Comment by Aliaksei-Halouka** [comment] 2021-11-16 10:47
Oh seem I really missed this parameter, I will definitely try it, thanks for the tip.
