### ISSUE TITLE
Correctly escape sql queries

### ISSUE THREAD

**Issue by alexjfisher** [albertodonato/query-exporter#21] opened 2020-01-30 11:48 UTC
I have a query which contains `DATE_FORMAT(CURDATE(), '%Y-%m-01 00:00:00')`.  In my config yaml, I have to escape the `%`s (ie. `DATE_FORMAT(CURDATE(), '%%Y-%%m-01 00:00:00')`

Otherwise I get the error
```
ERROR - query-exporter - query "query1" on database "db" failed: unsupported format character 'Y' (0x59) at index 144
```

Obviously escaping the % character myself wasn't hard to do (after a bit of googling), but ideally this would be handled in the application.

**Comment by albertodonato** [comment] 2020-01-30 22:15
I'm not sure if this can be done. the `%` sign has special meaning for python's DBAPI: https://www.python.org/dev/peps/pep-0249/#paramstyle

There seems to be an option in SQLAlchemy to remove the need for escaping if the query doesn't have parameters, but it seems it could be more confusing to uenable that behavior.

**Comment by alexjfisher** [comment] 2020-01-30 22:20
ok.  Thanks for looking.  Maybe just a README update would help other users.

**Comment by albertodonato** [comment] 2020-01-31 16:39
So, I dug this a bit deeper. The issue is that currently queries as passed as-is through sqlalchemy, so the parameter substitution is done by the underlying DB lib (mysql in this case). Per DBAPI spec, libraries can support any of those parameters styles.

I'm planning to switch to wrap the call in `sqlalchemy.text()`, which handles converting parameter passing style based on the target database dialect.
The downside of this is that it only supports named parameters (as `:param`), so use of positional arguments (such as `?`) won't be supported anymore.

By doing so, `%` won't need to be escaped anymore (and infact escaping it with `%%` will leave a single `%`).

It's a backward-incompatible change, so I'll do this as part of a 2.0 release, along with a few other cleanups.

**Closed** 2020-02-02 18:28 UTC

**Comment by albertodonato** [comment] 2020-02-03 08:24
With 2.0.0, you shouldn't need to escape `%` anymore
