### ISSUE TITLE
If connection is closed query-exporter does not attempt to reconnect.

### ISSUE THREAD

**Issue by invokermain** [albertodonato/query-exporter#56] opened 2020-07-15 09:45 UTC
**Describe the bug**

```2020-07-15 09:37:37,369 - DEBUG - query-exporter - updating metric "queries" inc 1 {database="db1",status="error"}
2020-07-15 09:37:37,371 - ERROR - query-exporter - query "replication_lag_communications" on database "db1" failed: This result object does not return rows. It has been closed automatically.
2020-07-15 09:37:37,371 - DEBUG - query-exporter - updating metric "queries" inc 1 {database="db1",status="error"}
2020-07-15 09:37:37,373 - ERROR - query-exporter - query "replication_lag_lastbooked" on database "db1" failed: (pyodbc.ProgrammingError) The cursor's connection has been closed.```


**To Reproduce**

0. keep-connected: true (not sure if affects behaviour)
1. Run one query that selects into a #temp table or any other non-row return query.
2. Run another query straight after, it will error.

**Expected**

Not sure if this is intended behaviour, in case it's not I would expect each query to be agnostic of what other queries are being run (so one bad query doesn't spoil every query).

**Comment by albertodonato** [comment] 2020-08-15 13:13
Could you please share your (sanitized as needed) config?

**Comment by albertodonato** [comment] 2021-03-14 09:29
I can't reproduce this error with the current version (either with or without `keep-connected: true`.

Closing the bug, please feel free to reopen if it still happens (in which case please attach a sample config and output running `-L DEBUG`.

**Closed by albertodonato** 2021-03-14 09:29 UTC
Labels: bug
